// PulseSense — Export Service
// Orchestrates: data fetch → HTML template build → expo-print → expo-sharing → cleanup

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { getDB } from '../hooks/useDB';
import { getProfile } from '../db/queries/profile';
import { getConditions } from '../db/queries/conditions';
import { getAllergies } from '../db/queries/allergies';
import { getContacts } from '../db/queries/contacts';
import { getActiveMedications } from '../db/queries/medications';
import { getVitalLogsByDateRange } from '../db/queries/vitals';
import { getAllAlerts } from '../db/queries/emergency';
import { getLast30DaysRange, formatTodayDisplay } from '../utils/dateUtils';
import {
  buildMedicalIdHtml,
  buildVitalsReportHtml,
  buildMedicationsHtml,
  buildAlertsHtml,
  buildFullReportHtml,
} from './pdfTemplates';

export type ExportType = 'medical_id' | 'vitals_report' | 'medications' | 'alerts' | 'full_report';

export interface ExportOptions {
  type: ExportType;
  vitalTypes?: string[]; // for vitals_report
  dateRange?: { start: string; end: string }; // for vitals_report
}

async function getExportData() {
  const db = await getDB();
  const [profile, conditions, allergies, contacts, medications, alerts] = await Promise.all([
    getProfile(db),
    getConditions(db),
    getAllergies(db),
    getContacts(db),
    getActiveMedications(db),
    getAllAlerts(db),
  ]);
  return { profile, conditions, allergies, contacts, medications, alerts };
}

export async function generateExport(options: ExportOptions): Promise<string> {
  const data = await getExportData();
  if (!data.profile) throw new Error('Profile not found');

  let html: string;

  switch (options.type) {
    case 'medical_id':
      html = buildMedicalIdHtml(
        data.profile,
        data.conditions,
        data.allergies,
        data.contacts
      );
      break;

    case 'vitals_report': {
      const range = options.dateRange || getLast30DaysRange();
      const db = await getDB();
      const vitals = await getVitalLogsByDateRange(db, range.start, range.end);
      html = buildVitalsReportHtml(
        data.profile,
        vitals,
        options.vitalTypes || ['bp', 'pulse', 'spo2', 'glucose', 'temperature', 'weight', 'pain']
      );
      break;
    }

    case 'medications':
      html = buildMedicationsHtml(data.profile, data.medications);
      break;

    case 'alerts':
      html = buildAlertsHtml(data.alerts);
      // Wrap with header and footer
      html = `
        <html>
        <head><style>
          body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1C2B3A; margin: 20px; }
          .header { background: #1A5F7A; color: white; padding: 14px 18px; border-radius: 4px; margin-bottom: 16px; }
          .header h1 { margin: 0; font-size: 18px; }
          .header p { margin: 3px 0; font-size: 10px; opacity: 0.85; }
          .section-title { font-size: 12px; font-weight: bold; color: #1A5F7A; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #1A5F7A; padding-bottom: 4px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
          th { background: #EEF4F7; text-align: left; padding: 7px 9px; border: 1px solid #CBD5E0; font-size: 10px; text-transform: uppercase; color: #1C2B3A; }
          td { padding: 7px 9px; border: 1px solid #CBD5E0; font-size: 10px; }
          tr:nth-child(even) { background: #F8FAFB; }
          .badge-danger { background: #FEE2E2; color: #991B1B; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
          .badge-warning { background: #FEF3C7; color: #D97706; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
          .badge-normal { background: #D1FAE5; color: #065F46; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
          .footer { margin-top: 28px; font-size: 9px; color: #9CA3AF; text-align: center; border-top: 1px solid #E5E7EB; padding-top: 10px; }
        </style></head>
        <body>
          <div class="header">
            <h1>Emergency Alerts — ${data.profile.full_name}</h1>
            <p>Report generated: ${formatTodayDisplay()}</p>
          </div>
          ${html}
          <div class="footer">Generated by PulseSense — for informational use only. Not a clinical document.</div>
        </body>
        </html>
      `;
      break;

    case 'full_report':
      html = buildFullReportHtml(
        data.profile,
        data.conditions,
        data.allergies,
        data.contacts,
        data.medications,
        data.alerts
      );
      break;

    default:
      throw new Error(`Unknown export type: ${options.type}`);
  }

  // Generate PDF
  const { uri } = await Print.printToFileAsync({ html, width: 595.28, height: 841.89 }); // A4
  return uri;
}

export async function sharePdf(uri: string): Promise<void> {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share PulseSense Report',
    });
  } else {
    throw new Error('Sharing is not available on this device');
  }
}

export async function cleanupPdf(uri: string): Promise<void> {
  try {
    const info = await FileSystem.getInfoAsync(uri);
    if (info.exists) {
      await FileSystem.deleteAsync(uri, { idempotent: true });
    }
  } catch {
    // Non-critical cleanup, ignore errors
  }
}

export async function exportAndShare(options: ExportOptions): Promise<void> {
  const uri = await generateExport(options);
  await sharePdf(uri);
  // expo-print writes to the OS temp/cache directory which is cleaned up
  // automatically by the OS. No explicit cleanup needed — deferred cleanup
  // can race with the share target reading the file.
}
