// PulseSense — PDF HTML Templates
// Generates HTML+CSS strings for expo-print to render as PDF

import { calculateAge, formatTodayDisplay } from '../utils/dateUtils';
import { formatDosage } from '../utils/dosageFormatter';

const BASE_STYLES = `
  body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1C2B3A; margin: 20px; }
  .header { background: #1A5F7A; color: white; padding: 14px 18px; border-radius: 4px; margin-bottom: 16px; }
  .header h1 { margin: 0; font-size: 18px; }
  .header p { margin: 3px 0; font-size: 10px; opacity: 0.85; }
  .section-title { font-size: 12px; font-weight: bold; color: #1A5F7A; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #1A5F7A; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
  th { background: #EEF4F7; text-align: left; padding: 7px 9px; border: 1px solid #CBD5E0; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #1C2B3A; }
  td { padding: 7px 9px; border: 1px solid #CBD5E0; font-size: 10px; }
  tr:nth-child(even) { background: #F8FAFB; }
  .badge-danger { background: #FEE2E2; color: #991B1B; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
  .badge-warning { background: #FEF3C7; color: #D97706; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
  .badge-normal { background: #D1FAE5; color: #065F46; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
  .footer { margin-top: 28px; font-size: 9px; color: #9CA3AF; text-align: center; border-top: 1px solid #E5E7EB; padding-top: 10px; }
  .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); opacity: 0.04; font-size: 60px; color: #1A5F7A; font-weight: bold; pointer-events: none; }
`;

function headerHtml(name: string, dob: string, bloodGroup: string | null, sex: string | null) {
  return `
    <div class="header">
      <h1>Medical Record — ${name}</h1>
      <p>DOB: ${dob} | Age: ${calculateAge(dob)} | Blood Group: ${bloodGroup || 'Unknown'} | Sex: ${sex || 'Not specified'}</p>
      <p>Report generated: ${formatTodayDisplay()}</p>
    </div>
  `;
}

function sectionTitle(title: string) {
  return `<div class="section-title">${title}</div>`;
}

function footerHtml() {
  return '<div class="footer">Generated by PulseSense — for informational use only. Not a clinical document.</div>';
}

export function buildFullReportHtml(
  profile: { full_name: string; dob: string; blood_group: string | null; sex: string | null },
  conditions: { name: string; type: string | null; severity: string | null; diagnosed_date: string | null; notes: string | null }[],
  allergies: { name: string; severity: string | null; reaction: string | null }[],
  contacts: { name: string; relationship: string | null; phone: string; contact_type?: string }[],
  medications: { prescription_date: string; prescribing_doctor: string | null; diagnosis_notes: string | null; is_active: number; items: { medicine_name: string; strength: string | null; dose_morning: number; dose_afternoon: number; dose_night: number; timing: string | null; duration: string | null }[] }[],
  alerts: { title: string; message: string; severity_level: string; created_at: string }[]
): string {
  const parts = [
    buildMedicalIdHtml(profile, conditions, allergies, contacts),
    `<div style="page-break-before: always;"></div>`,
    buildMedicationsHtml(profile, medications),
    `<div style="page-break-before: always;"></div>`,
    buildAlertsHtml(alerts),
  ];

  return wrapHtml(parts.join('\n'));
}

export function buildMedicalIdHtml(
  profile: { full_name: string; dob: string; blood_group: string | null; sex: string | null },
  conditions: { name: string; type: string | null; severity: string | null; diagnosed_date: string | null; notes: string | null }[],
  allergies: { name: string; severity: string | null; reaction: string | null }[],
  contacts: { name: string; relationship: string | null; phone: string; contact_type?: string }[]
): string {
  const conditionsHtml = conditions.length > 0
    ? conditions.map((c) => {
        const severityBadge = c.severity
          ? `<span class="badge-${c.severity === 'severe' ? 'danger' : c.severity === 'moderate' ? 'warning' : 'normal'}">${c.severity}</span>`
          : '';
        return `<tr><td>${c.name}</td><td>${c.type || '-'}</td><td>${c.diagnosed_date || '-'}</td><td>${severityBadge}</td><td>${c.notes || '-'}</td></tr>`;
      }).join('')
    : '<tr><td colspan="5" style="text-align:center; color:#9CA3AF;">No conditions recorded</td></tr>';

  const allergiesHtml = allergies.length > 0
    ? allergies.map((a) => {
        const sevBadge = a.severity
          ? `<span class="badge-${a.severity === 'life-threatening' || a.severity === 'severe' ? 'danger' : a.severity === 'moderate' ? 'warning' : 'normal'}">${a.severity}</span>`
          : '';
        return `<tr><td>${a.name}</td><td>${sevBadge}</td><td>${a.reaction || '-'}</td></tr>`;
      }).join('')
    : '<tr><td colspan="3" style="text-align:center; color:#9CA3AF;">No allergies recorded</td></tr>';

  const contactsHtml = contacts.length > 0
    ? contacts.map((c) => {
        const typeLabel = c.contact_type === 'doctor' ? 'Doctor' : 'Emergency';
        return `<tr><td>${c.name}</td><td>${c.relationship || '-'}</td><td>${typeLabel}</td><td>${c.phone}</td></tr>`;
      }).join('')
    : '<tr><td colspan="4" style="text-align:center; color:#9CA3AF;">No emergency contacts</td></tr>';

  return `
    ${headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex)}
    ${sectionTitle('Medical Conditions')}
    <table><thead><tr><th>Condition</th><th>Type</th><th>Diagnosed</th><th>Severity</th><th>Notes</th></tr></thead><tbody>${conditionsHtml}</tbody></table>
    ${sectionTitle('Allergies')}
    <table><thead><tr><th>Allergen</th><th>Severity</th><th>Reaction</th></tr></thead><tbody>${allergiesHtml}</tbody></table>
    ${sectionTitle('Emergency Contacts')}
    <table><thead><tr><th>Name</th><th>Relationship</th><th>Type</th><th>Phone</th></tr></thead><tbody>${contactsHtml}</tbody></table>
    ${footerHtml()}
  `;
}

export function buildVitalsReportHtml(
  profile: { full_name: string; dob: string; blood_group: string | null; sex: string | null },
  vitals: {
    logged_at_display: string;
    bp_sys: number | null; bp_dia: number | null;
    pulse: number | null; spo2: number | null;
    glucose_value: number | null; glucose_context: string | null;
    temp_value: number | null; weight_value: number | null;
    pain_level: number | null; pain_location: string | null;
    notes: string | null;
  }[],
  selectedTypes: string[]
): string {
  const rowsHtml = vitals.map((v) => {
    const cells = selectedTypes.map((type) => {
      switch (type) {
        case 'bp': return v.bp_sys ? `${v.bp_sys}/${v.bp_dia}` : '-';
        case 'pulse': return v.pulse != null ? `${v.pulse}` : '-';
        case 'spo2': return v.spo2 != null ? `${v.spo2}%` : '-';
        case 'glucose': return v.glucose_value != null ? `${v.glucose_value} ${v.glucose_context || ''}` : '-';
        case 'temperature': return v.temp_value != null ? `${v.temp_value}°` : '-';
        case 'weight': return v.weight_value != null ? `${v.weight_value}` : '-';
        case 'pain': return v.pain_level != null ? `${v.pain_level}/10 ${v.pain_location || ''}` : '-';
        default: return '-';
      }
    });
    return `<tr><td>${v.logged_at_display}</td>${cells.map((c) => `<td>${c}</td>`).join('')}</tr>`;
  }).join('');

  const headers = selectedTypes.map((t) => `<th>${t.charAt(0).toUpperCase() + t.slice(1)}</th>`).join('');

  return `
    ${headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex)}
    ${sectionTitle('Vitals History')}
    <table><thead><tr><th>Date/Time</th>${headers}</tr></thead><tbody>${rowsHtml || '<tr><td colspan="9" style="text-align:center; color:#9CA3AF;">No vitals recorded in selected range</td></tr>'}</tbody></table>
    ${footerHtml()}
  `;
}

export function buildMedicationsHtml(
  profile: { full_name: string; dob: string; blood_group: string | null; sex: string | null },
  medications: { prescription_date: string; prescribing_doctor: string | null; diagnosis_notes: string | null; is_active: number; items: { medicine_name: string; strength: string | null; dose_morning: number; dose_afternoon: number; dose_night: number; timing: string | null; duration: string | null }[] }[]
): string {
  const medsHtml = medications.map((m) => {
    const itemsHtml = m.items.map((i) => {
      const dose = formatDosage(i.dose_morning, i.dose_afternoon, i.dose_night);
      return `<tr><td>${i.medicine_name}</td><td>${i.strength || '-'}</td><td>${dose} (M-A-N)</td><td>${i.timing || '-'}</td><td>${i.duration || '-'}</td></tr>`;
    }).join('');
    const status = m.is_active ? 'Active' : 'Inactive';
    return `
      <tr style="background:#EEF4F7;"><td colspan="5"><strong>Rx: ${m.prescription_date}</strong> | Dr: ${m.prescribing_doctor || '-'} | ${status} | ${m.diagnosis_notes || ''}</td></tr>
      ${itemsHtml}
    `;
  }).join('');

  return `
    ${headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex)}
    ${sectionTitle('Medications')}
    <table><thead><tr><th>Medicine</th><th>Strength</th><th>Dosage (M-A-N)</th><th>Timing</th><th>Duration</th></tr></thead><tbody>${medsHtml || '<tr><td colspan="5" style="text-align:center; color:#9CA3AF;">No medications recorded</td></tr>'}</tbody></table>
    ${footerHtml()}
  `;
}

export function buildAlertsHtml(
  alerts: { title: string; message: string; severity_level: string; created_at: string }[]
): string {
  const alertsHtml = alerts.length > 0
    ? alerts.map((a) => {
        const badgeClass = a.severity_level === 'EMERGENCY_NOW' ? 'danger' : a.severity_level === 'URGENT_SAME_DAY' ? 'warning' : 'normal';
        return `<tr><td>${a.created_at}</td><td><span class="badge-${badgeClass}">${a.severity_level}</span></td><td>${a.title}</td><td>${a.message}</td></tr>`;
      }).join('')
    : '<tr><td colspan="4" style="text-align:center; color:#9CA3AF;">No emergency alerts recorded</td></tr>';

  return `
    <div style="page-break-before: always;"></div>
    ${sectionTitle('Emergency Alerts History')}
    <table><thead><tr><th>Date/Time</th><th>Severity</th><th>Title</th><th>Details</th></tr></thead><tbody>${alertsHtml}</tbody></table>
    ${footerHtml()}
  `;
}

export function wrapHtml(content: string): string {
  return `
    <html>
    <head>
      <style>${BASE_STYLES}</style>
    </head>
    <body>
      <div class="watermark">PulseSense</div>
      ${content}
    </body>
    </html>
  `;
}
