import { calculateAge, formatTodayDisplay, isoToDisplay } from '../utils/dateUtils';
import { formatDosage } from '../utils/dosageFormatter';
import { formatVitalHtmlCell, VITAL_HEADERS } from '../utils/vitalFormatters';

function escapeHtml(s: string | null | undefined): string {
  if (s == null) return '';
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
}

const BASE_STYLES = `
  body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1C2B3A; margin: 20px; }
  .report-header { background: #1A5F7A; color: white; border-radius: 4px; margin-bottom: 16px; padding: 14px 18px; width: 100%; }
  .report-header h1 { margin: 0 0 8px; font-size: 18px; color: white; }
  .header-info { font-size: 10px; color: rgba(255,255,255,0.85); }
  .header-info td { padding: 2px 16px 2px 0; vertical-align: top; }
  .header-info .label { font-weight: 600; opacity: 0.6; padding-right: 4px; }
  .header-generated { font-size: 9px; color: rgba(255,255,255,0.6); margin-top: 6px; }
  .header-photo-cell { width: 70px; text-align: right; vertical-align: top; }
  .header-photo { width: 56px; height: 56px; border-radius: 50%; border: 2px solid rgba(255,255,255,0.6); object-fit: cover; }
  .header-photo-placeholder { width: 56px; height: 56px; border-radius: 50%; border: 2px solid rgba(255,255,255,0.3); background: rgba(255,255,255,0.1); text-align: center; line-height: 56px; font-size: 22px; color: rgba(255,255,255,0.4); }
  .section-title { font-size: 12px; font-weight: bold; color: #1A5F7A; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #1A5F7A; padding-bottom: 4px; }
  table.content-table { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
  th { background: #EEF4F7; text-align: left; padding: 7px 9px; border: 1px solid #CBD5E0; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #1C2B3A; }
  td { padding: 7px 9px; border: 1px solid #CBD5E0; font-size: 10px; }
  tr:nth-child(even) { background: #F8FAFB; }
  .badge-danger { background: #FEE2E2; color: #991B1B; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
  .badge-warning { background: #FEF3C7; color: #D97706; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
  .badge-normal { background: #D1FAE5; color: #065F46; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
  .disclaimer { margin-top: 28px; font-size: 9px; color: #9CA3AF; text-align: center; border-top: 1px solid #E5E7EB; padding-top: 10px; font-weight: bold; }
  .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); opacity: 0.04; font-size: 60px; color: #1A5F7A; font-weight: bold; pointer-events: none; }
  .notes-cell { font-style: italic; color: #4B5563; max-width: 180px; word-wrap: break-word; }
`;

function photoCellHtml(photoUri?: string | null): string {
  if (photoUri) {
    return `<td class="header-photo-cell" rowspan="2"><img src="${escapeHtml(photoUri)}" alt="Profile" class="header-photo" /></td>`;
  }
  return `<td class="header-photo-cell" rowspan="2"><div class="header-photo-placeholder">&#9787;</div></td>`;
}

function headerHtml(name: string, dob: string, bloodGroup: string | null, sex: string | null, photoUri?: string | null) {
  return `
    <div class="report-header">
      <table style="width:100%; border: none; margin: 0;"><tr>
        <td style="padding:0; border:none; vertical-align:top;">
          <h1>Medical Record — ${escapeHtml(name)}</h1>
          <table class="header-info" style="border:none; margin:0;"><tr>
            <td style="padding:2px 16px 2px 0; border:none;"><span class="label">DOB:</span> ${escapeHtml(dob)}</td>
            <td style="padding:2px 16px 2px 0; border:none;"><span class="label">Age:</span> ${calculateAge(dob)}</td>
            <td style="padding:2px 16px 2px 0; border:none;"><span class="label">Blood:</span> ${escapeHtml(bloodGroup) || 'Unknown'}</td>
            <td style="padding:2px 16px 2px 0; border:none;"><span class="label">Sex:</span> ${escapeHtml(sex) || 'Not specified'}</td>
          </tr></table>
          <div class="header-generated">Report generated: ${formatTodayDisplay()}</div>
        </td>
        ${photoCellHtml(photoUri)}
      </tr></table>
    </div>
  `;
}

function sectionTitle(title: string) {
  return `<div class="section-title">${escapeHtml(title)}</div>`;
}

function disclaimerHtml() {
  return '<div class="disclaimer">Generated by PulseSense — for informational use only. Not a clinical document.</div>';
}

export function buildFullReportHtml(
  profile: PdfProfile,
  conditions: { name: string; type: string | null; severity: string | null; diagnosed_date: string | null; notes: string | null }[],
  allergies: { name: string; severity: string | null; reaction: string | null }[],
  contacts: { name: string; relationship: string | null; phone: string; contact_type?: string }[],
  medications: { prescription_date: string; prescribing_doctor: string | null; diagnosis_notes: string | null; is_active: number; items: { medicine_name: string; strength: string | null; dose_morning: number; dose_afternoon: number; dose_night: number; timing: string | null; duration: string | null }[] }[],
  alerts: { title: string; message: string; severity_level: string; created_at: string }[]
): string {
  const parts = [
    headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex, profile.photo_uri),
    '<div style="page-break-inside: avoid;">',
    buildMedicalIdSections(conditions, allergies, contacts),
    '</div>',
    medications.length > 0 ? '<div style="page-break-inside: avoid;">' : '',
    medications.length > 0 ? buildMedicationsSections(medications) : '',
    medications.length > 0 ? '</div>' : '',
    alerts.length > 0 ? '<div style="page-break-inside: avoid;">' : '',
    alerts.length > 0 ? buildAlertsSections(alerts) : '',
    alerts.length > 0 ? '</div>' : '',
    disclaimerHtml(),
  ];
  return wrapHtml(parts.join('\n'));
}

function buildMedicalIdSections(
  conditions: { name: string; type: string | null; severity: string | null; diagnosed_date: string | null; notes: string | null }[],
  allergies: { name: string; severity: string | null; reaction: string | null }[],
  contacts: { name: string; relationship: string | null; phone: string; contact_type?: string }[]
): string {
  const conditionsHtml = conditions.length > 0
    ? conditions.map((c) => {
        const severityBadge = c.severity
          ? `<span class="badge-${c.severity === 'severe' ? 'danger' : c.severity === 'moderate' ? 'warning' : 'normal'}">${escapeHtml(c.severity)}</span>`
          : '';
        return `<tr><td>${escapeHtml(c.name)}</td><td>${escapeHtml(c.type) || '-'}</td><td>${escapeHtml(c.diagnosed_date) || '-'}</td><td>${severityBadge}</td><td>${escapeHtml(c.notes) || '-'}</td></tr>`;
      }).join('')
    : '<tr><td colspan="5" style="text-align:center; color:#9CA3AF;">No conditions recorded</td></tr>';

  const allergiesHtml = allergies.length > 0
    ? allergies.map((a) => {
        const sevBadge = a.severity
          ? `<span class="badge-${a.severity === 'life-threatening' || a.severity === 'severe' ? 'danger' : a.severity === 'moderate' ? 'warning' : 'normal'}">${escapeHtml(a.severity)}</span>`
          : '';
        return `<tr><td>${escapeHtml(a.name)}</td><td>${sevBadge}</td><td>${escapeHtml(a.reaction) || '-'}</td></tr>`;
      }).join('')
    : '<tr><td colspan="3" style="text-align:center; color:#9CA3AF;">No allergies recorded</td></tr>';

  const contactsHtml = contacts.length > 0
    ? contacts.map((c) => {
        const typeLabel = c.contact_type === 'doctor' ? 'Doctor' : 'Emergency';
        return `<tr><td>${escapeHtml(c.name)}</td><td>${escapeHtml(c.relationship) || '-'}</td><td>${typeLabel}</td><td>${escapeHtml(c.phone)}</td></tr>`;
      }).join('')
    : '<tr><td colspan="4" style="text-align:center; color:#9CA3AF;">No emergency contacts</td></tr>';

  return `
    ${sectionTitle('Medical Conditions')}
    <table><thead><tr><th>Condition</th><th>Type</th><th>Diagnosed</th><th>Severity</th><th>Notes</th></tr></thead><tbody>${conditionsHtml}</tbody></table>
    ${sectionTitle('Allergies')}
    <table><thead><tr><th>Allergen</th><th>Severity</th><th>Reaction</th></tr></thead><tbody>${allergiesHtml}</tbody></table>
    ${sectionTitle('Emergency Contacts')}
    <table><thead><tr><th>Name</th><th>Relationship</th><th>Type</th><th>Phone</th></tr></thead><tbody>${contactsHtml}</tbody></table>
  `;
}

function buildMedicationsSections(
  medications: { prescription_date: string; prescribing_doctor: string | null; diagnosis_notes: string | null; is_active: number; items: { medicine_name: string; strength: string | null; dose_morning: number; dose_afternoon: number; dose_night: number; timing: string | null; duration: string | null }[] }[]
): string {
  const medsHtml = medications.map((m) => {
    const itemsHtml = m.items.map((i) => {
      const dose = formatDosage(i.dose_morning, i.dose_afternoon, i.dose_night);
      return `<tr><td>${escapeHtml(i.medicine_name)}</td><td>${escapeHtml(i.strength) || '-'}</td><td>${dose} (M-A-N)</td><td>${escapeHtml(i.timing) || '-'}</td><td>${escapeHtml(i.duration) || '-'}</td></tr>`;
    }).join('');
    const status = m.is_active ? 'Active' : 'Inactive';
    return `
      <tr style="background:#EEF4F7;"><td colspan="5"><strong>Rx: ${escapeHtml(m.prescription_date)}</strong> | Dr: ${escapeHtml(m.prescribing_doctor) || '-'} | ${escapeHtml(status)} | ${escapeHtml(m.diagnosis_notes) || ''}</td></tr>
      ${itemsHtml}
    `;
  }).join('');

  return `
    ${sectionTitle('Medications')}
    <table><thead><tr><th>Medicine</th><th>Strength</th><th>Dosage (M-A-N)</th><th>Timing</th><th>Duration</th></tr></thead><tbody>${medsHtml || '<tr><td colspan="5" style="text-align:center; color:#9CA3AF;">No medications recorded</td></tr>'}</tbody></table>
  `;
}

function buildAlertsSections(
  alerts: { title: string; message: string; severity_level: string; created_at: string }[]
): string {
  const alertsHtml = alerts.length > 0
    ? alerts.map((a) => {
        const badgeClass = a.severity_level === 'EMERGENCY_NOW' ? 'danger' : a.severity_level === 'URGENT_SAME_DAY' ? 'warning' : 'normal';
        return `<tr><td>${a.created_at ? isoToDisplay(a.created_at) : a.created_at}</td><td><span class="badge-${badgeClass}">${escapeHtml(a.severity_level)}</span></td><td>${escapeHtml(a.title)}</td><td>${escapeHtml(a.message)}</td></tr>`;
      }).join('')
    : '<tr><td colspan="4" style="text-align:center; color:#9CA3AF;">No emergency alerts recorded</td></tr>';

  return `
    ${sectionTitle('Emergency Alerts History')}
    <table><thead><tr><th>Date/Time</th><th>Severity</th><th>Title</th><th>Details</th></tr></thead><tbody>${alertsHtml}</tbody></table>
  `;
}

export function buildMedicalIdHtml(
  profile: PdfProfile,
  conditions: { name: string; type: string | null; severity: string | null; diagnosed_date: string | null; notes: string | null }[],
  allergies: { name: string; severity: string | null; reaction: string | null }[],
  contacts: { name: string; relationship: string | null; phone: string; contact_type?: string }[],
  medications: { prescription_date: string; prescribing_doctor: string | null; diagnosis_notes: string | null; is_active: number; items: { medicine_name: string; strength: string | null; dose_morning: number; dose_afternoon: number; dose_night: number; timing: string | null; duration: string | null }[] }[] = []
): string {
  return `
    ${headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex, profile.photo_uri)}
    ${buildMedicalIdSections(conditions, allergies, contacts)}
    ${medications.length > 0 ? buildMedicationsSections(medications) : ''}
    ${disclaimerHtml()}
  `;
}

export function buildVitalsReportHtml(
  profile: PdfProfile,
  vitals: {
    logged_at_display: string;
    bp_sys: number | null; bp_dia: number | null;
    pulse: number | null; spo2: number | null;
    glucose_value: number | null; glucose_unit: string; glucose_context: string | null;
    temp_value: number | null; temp_unit: string; weight_value: number | null; weight_unit: string;
    pain_level: number | null; pain_location: string | null;
    notes: string | null;
  }[],
  selectedTypes: string[]
): string {
  const showNotes = vitals.some((v) => v.notes != null && v.notes.length > 0);
  const headerCells = selectedTypes.map((t) => {
    const normalizedType = t === 'temperature' ? 'temp' : t;
    return `<th>${VITAL_HEADERS[normalizedType] || t}</th>`;
  }).join('');
  const notesHeader = showNotes ? '<th>Notes</th>' : '';
  const headers = headerCells + notesHeader;

  const rowsHtml = vitals.map((v) => {
    const cells = selectedTypes.map((type) => {
      const normalizedType = type === 'temperature' ? 'temp' : type;
      return formatVitalHtmlCell(normalizedType, v);
    });
    const notesCell = showNotes ? `<td class="notes-cell">${escapeHtml(v.notes) || ''}</td>` : '';
    return `<tr><td>${v.logged_at_display}</td>${cells.map((c) => `<td>${c}</td>`).join('')}${notesCell}</tr>`;
  }).join('');

  return `
    ${headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex, profile.photo_uri)}
    ${sectionTitle('Vitals History')}
    <table><thead><tr><th>Date/Time</th>${headers}</tr></thead><tbody>${rowsHtml || '<tr><td colspan="9" style="text-align:center; color:#9CA3AF;">No vitals recorded in selected range</td></tr>'}</tbody></table>
    ${disclaimerHtml()}
  `;
}

export function buildMedicationsHtml(
  profile: PdfProfile,
  medications: { prescription_date: string; prescribing_doctor: string | null; diagnosis_notes: string | null; is_active: number; items: { medicine_name: string; strength: string | null; dose_morning: number; dose_afternoon: number; dose_night: number; timing: string | null; duration: string | null }[] }[]
): string {
  return `
    ${headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex, profile.photo_uri)}
    ${buildMedicationsSections(medications)}
    ${disclaimerHtml()}
  `;
}

export function buildAlertsHtml(
  alerts: { title: string; message: string; severity_level: string; created_at: string }[],
  profile?: PdfProfile | null
): string {
  const header = profile ? headerHtml(profile.full_name, profile.dob, profile.blood_group, profile.sex, profile.photo_uri) : '';
  return `
    ${header}
    ${sectionTitle('Emergency Alerts History')}
    <table><thead><tr><th>Date/Time</th><th>Severity</th><th>Title</th><th>Details</th></tr></thead><tbody>${buildAlertsRows(alerts)}</tbody></table>
    ${disclaimerHtml()}
  `;
}

function buildAlertsRows(
  alerts: { title: string; message: string; severity_level: string; created_at: string }[]
): string {
  if (alerts.length === 0) {
    return '<tr><td colspan="4" style="text-align:center; color:#9CA3AF;">No emergency alerts recorded</td></tr>';
  }
  return alerts.map((a) => {
    const badgeClass = a.severity_level === 'EMERGENCY_NOW' ? 'danger' : a.severity_level === 'URGENT_SAME_DAY' ? 'warning' : 'normal';
    return `<tr><td>${a.created_at ? isoToDisplay(a.created_at) : a.created_at}</td><td><span class="badge-${badgeClass}">${escapeHtml(a.severity_level)}</span></td><td>${escapeHtml(a.title)}</td><td>${escapeHtml(a.message)}</td></tr>`;
  }).join('');
}

export function wrapHtml(content: string): string {
  return `
    <html>
    <head>
      <style>${BASE_STYLES}</style>
    </head>
    <body>
      <div class="watermark">PulseSense</div>
      ${content}
    </body>
    </html>
  `;
}
